apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: hello-node
  name: hello-node-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      run: hello-node
  template:
    metadata:
      labels:
        run: hello-node 
    spec: 
      containers:
      - image: kmaster.example.com:5000/hello-node:alpine
        name: hello-node
