apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: ReplicaSet
  metadata:
    creationTimestamp: "2019-02-23T16:45:06Z"
    generation: 1
    labels:
      run: hello-node
    name: hello-node-replicaset
    namespace: default
    resourceVersion: "53218"
    selfLink: /apis/extensions/v1beta1/namespaces/default/replicasets/hello-node-replicaset
    uid: 5fb6caec-378a-11e9-a01c-52540075dc3d
  spec:
    replicas: 3
    selector:
      matchLabels:
        run: hello-node
    template:
      metadata:
        creationTimestamp: null
        labels:
          run: hello-node
      spec:
        containers:
        - image: kmaster.example.com:5000/hello-node:alpine
          imagePullPolicy: IfNotPresent
          name: hello-node
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 3
    fullyLabeledReplicas: 3
    observedGeneration: 1
    readyReplicas: 3
    replicas: 3
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
