apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2019-02-23T16:48:18Z"
  generation: 2
  labels:
    run: hello-node
  name: hello-node-deploy
  namespace: default
  resourceVersion: "53608"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/hello-node-deploy
  uid: d22d9a85-378a-11e9-a01c-52540075dc3d
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 5
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      run: hello-node
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: hello-node
    spec:
      containers:
      - image: kmaster.example.com:5000/hello-node:alpine
        imagePullPolicy: IfNotPresent
        name: hello-node
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 5
  conditions:
  - lastTransitionTime: "2019-02-23T16:48:42Z"
    lastUpdateTime: "2019-02-23T16:48:42Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
  readyReplicas: 5
  replicas: 5
  updatedReplicas: 5
