apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: "2019-02-23T16:39:13Z"
    name: hello-node-pod
    namespace: default
    resourceVersion: "52636"
    selfLink: /api/v1/namespaces/default/pods/hello-node-pod
    uid: 8d4bf092-3789-11e9-a01c-52540075dc3d
  spec:
    containers:
    - image: kmaster.example.com:5000/hello-node:alpine
      imagePullPolicy: IfNotPresent
      name: hello-node
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: default-token-jgbhx
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: kworker1.example.com
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: default-token-jgbhx
      secret:
        defaultMode: 420
        secretName: default-token-jgbhx
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2019-02-23T16:39:13Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2019-02-23T16:39:15Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2019-02-23T16:39:15Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2019-02-23T16:39:13Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: docker://dbf427ac7d1ad4f654ec32b3646b8f2600da88bd9e9afca915f184af5b8b5c87
      image: kmaster.example.com:5000/hello-node:alpine
      imageID: docker-pullable://kmaster.example.com:5000/hello-node@sha256:5483a9b7ba7492c4cda6e024870e27f643f74a5d745a8ba08b53607e8391eba9
      lastState: {}
      name: hello-node
      ready: true
      restartCount: 0
      state:
        running:
          startedAt: "2019-02-23T16:39:14Z"
    hostIP: 172.42.42.101
    phase: Running
    podIP: 10.244.1.62
    qosClass: BestEffort
    startTime: "2019-02-23T16:39:13Z"
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
