apiVersion: v1
kind: Pod
metadata:
  name: busybox190304
spec:
  volumes:
  - name: host-volume
    persistentVolumeClaim:
      claimName: pvc-nfs190304
  containers:
  - image: busybox
    name: busybox
    command: ["/bin/sh"]
    args: ["-c", "sleep 600"]
    volumeMounts:
    - name: host-volume
      mountPath: /mydata
