apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs190304
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
