apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    run: local
  name: pv-hostpath
spec:
  storageClassName: manual
#  persistentVolumeReclaimPolicy: Retain
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
#    path: "/home/vagrant/kube"
    path: "/tmp/kube"
  
