apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: nginx190304
  name: nginx190304-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      run: nginx190304
  template:
    metadata:
      labels:
        run: nginx190304
    spec:
      volumes:
      - name: www
        persistentVolumeClaim:
          claimName: pvc-nfs-pv1
      containers:
      - image: nginx
        name: nginx
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html

---

apiVersion: v1
kind: Service
metadata:
  labels:
    run: nginx190304
  name: nginx190304-service
spec:
  ports:
  - nodePort: 30500
    port: 80
  selector:
    run: nginx190304
  type: NodePort
