apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-pv0
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 172.42.42.100
    path: "/var/kubedata/nfsshare190304/pv0"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-pv1
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 172.42.42.100
    path: "/var/kubedata/nfsshare190304/pv1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-pv2
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 172.42.42.100
    path: "/var/kubedata/nfsshare190304/pv2"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-pv3
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 172.42.42.100
    path: "/var/kubedata/nfsshare190304/pv3"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-pv4
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 172.42.42.100
    path: "/var/kubedata/nfsshare190304/pv4"
